### PR TITLE
nixd/regression: fixed arrow direction

### PR DESCRIPTION
**Pull request by JayPankajPatel**
Fixes: #32 

Fixed a mistake where the arrow was not facing the same direction as the other arrows in the rest of the file.

### CODE REVIEW

**Comment by inclyc** [comment]
Thanks for contributing :)

Actually there are exactly same mistakes (i.e. incorrect arrow direction for `initialize(0)`) in our tests (I just employed copy-paste to write these regression tests). Can you fix them all in this PR? e.g.

https://github.com/inclyc/nixd/blob/2ee1ef796dd6dd5f0bc8cc4a3bc804972018c973/tools/nixd/test/initialize.md?plain=1#L5

> facing the same direction as the other arrows in the rest of the file

The directions is not supposed to be identical, instead it denotes the direction LSP server interacting with clients. For example, the messages with `<--` means it was sent by the client to the server (I've not documented this yet).

**Comment by JayPankajPatel** [comment]
Yes I’ll be happy too!
Thanks for the feedback, I’ll be careful not to make assumptions. Yeah it’s clear it is a server interaction to be frank I didn’t read much into but, I’ll be more careful and mindful.

**Review by inclyc — APPROVED** [review]

**Comment by JayPankajPatel** [comment]
Fixes: #32 

Added fix to all affected files.

**Comment by JayPankajPatel** [comment]
Thanks for being my first contribution to an open-source project!

**Pull request merged**
